allowBuilds:
    "@alicloud/openapi-core": true
    "@prisma/engines": true
    better-sqlite3: true
    core-js: true
    esbuild: true
    prisma: true
    sharp: true
    unrs-resolver: true

minimumReleaseAgeExclude:
    - "@1adybug/eslint"
    - "@1adybug/prettier"
    - "@1adybug/prettier-plugin-block-padding"
    - "@1adybug/prettier-plugin-remove-braces"
    - "@1adybug/prettier-plugin-sort-imports"
    - "@1adybug/xlsx"
    - deepsea-components
    - deepsea-tools
    - sdrr
    - soda-hooks
    - soda-tanstack-query
    - soda-react
    - soda-type
    - react-router@8.3.0
